title: Oceanos NTUA
logo: /assets/img/logo.png
author:
  email: oceanos.ntua@gmail.com

theme: jekyll-theme-bootstrap
minima:
  social_links:
    facebook: oceanos.ntua
    instagram: oceanos_ntua
    youtube_channel: UCyVxOwCrgLrMhWwGyk2rNLg
